### ISSUE TITLE
HOW DO I BUY OR CRREATE AN UNOFFICIAL  SERVER IN TEK LAUNCHER

### ISSUE THREAD

**Issue by BoNoX057** [Nuclearistt/TEKWrapper#1]
I WANT TO PLAY WITH MY FRIENDS ARK SURVIVAL EVOLVED IN TEK LAUCNHER IN AN UNOFFICIAL SERVER WE BUY IT OR ANYTHING WE JUST WANT TO PLAY PRIVETLY AN DLC WITH MODS IN TEK LAUCNHER AND WE DONT KNOW HOW AND WE DONT TO PLAY NON DEDICATED OR HOSTING SESSIONS CUZ IT DOESNT WORK FOR US SO PLEAASE CAN ANYONE HELP?

**Comment by BoNoX057** [comment]
@Nuclearistt

**Comment by noxnoire** [comment]
if u still looking for help on this matter dm me on discord noxnoire.0
